version: '3'

services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - learn_nest

networks:
  learn_nest: