version: '3'

services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - learn_nest
  
  nest-app:
    image: nest-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - learn_nest

networks:
  learn_nest: